// promises : 3 states : pending, fulfilled, rejected
// now laer or never

function getdata() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve('data fetched');
        },3000);
    });    
}
getdata() 
    .then(result =>{
        console.log(result);
    })
    .catch(error => {
        console.error(error);
    })

//async fn is adding try catch blocks instead of then,catch,etc
async function handledata() {
    try{
        const result = await handledata() ;
        console.log(result);
    }
    catch{
        console.error(error);
    }
}    
